
version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://todo:todo@db:5432/todo
      JWT_SECRET: supersecret_dev_key_change_me
      ACCESS_TOKEN_EXPIRE_MINUTES: 120
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: {}
